### ISSUE TITLE
Translate prisoners dilemma tutorial to text format

### ISSUE THREAD

**Issue by JamesPHoughton** [empiricaly/docsv2#1]
@mykoal will take on this task, and @jamesphoughton will support

# User Stories
>"As a new user of Empirica, I want to walk through an instructional tutorial that helps me build a new experiment from scratch, so that I can understand the steps to create a new experiment, and so that I can use it as a jumping-off point for building my own experiment."

>"As an instructor of Empirica tutorials at live events, I want to provide participants with a written resource that covers the steps I am teaching, so that students can use it as a reference during and after the tutorial to build the demo experiment."

# Background
I (@jamesphoughton) put together a tutorial on building the prisoner's dilemma in Empirica V2 for the Sage presentation with @alsobay. It's designed to cover some basic front end, server-side callbacks, and managing treatment files, and takes about 30 minutes at top speed. We should translate this tutorial into long-form text that can be included in this documentation, probably to replace (or go alongside) this:  https://github.com/empiricaly/docsv2/tree/main/guides/tutorial-your-first-experiment. 

The long-form tutorial has the advantage of a live/recorded demo in that we can link out to other resources/documentation at the appropriate places, so building this tutorial will not be just a matter of writing down what is in the demo. We should also think carefully about what additional learning resources exist for people walking through the tutorial, and where in the tutorial we should link out to them.

# Materials
- There is a video recording of one of my practice runs here: https://www.youtube.com/watch?v=1CiAwk-yrt8
- The GH repo containing the completed code (possibly with slight differences in variable names - need to check) here: https://github.com/JamesPHoughton/prisonersDilemmaDemo
- My script for giving the tutorial (with all the copy/paste code) is here: https://github.com/JamesPHoughton/empirica-V2-Tutorial/issues/1 (This is probably a more reliable source for up-to-date code)
- The existing tutorial will probably be a good resource for thinking about structure/formatting, plus any other ideas that are helpful but I didn't include in the speed-run video: https://github.com/empiricaly/docsv2/tree/main/guides/tutorial-your-first-experiment

# Steps
- [ ] @jamesphoughton and @mykoal check in with @npaton and @amaatouq about the code in https://github.com/JamesPHoughton/prisonersDilemmaDemo,   to see if they recommend any different approaches or code improvements before we make this a canonical example
- [ ] @mykoal walk through the tutorial and build the experiment, make notes for yourself on everything that is confusing or difficult, and what you did to fix it, what websites were helpful, and how your understanding changed by walking through it
- [ ] @mykoal fork this repo  and create a new directory in /guides to contain the tutorial pages
- [ ] @mykoal set up the overall structure based on the resources above
- [ ] @mykoal, @jamesphoughton check in about the proposed structure, create a draft PR just for the structure
- [ ] spend time writing text and formatting code, etc, update the PR
- [ ] Sit down with a student who hasn't used empirica before and have them go through the tutorial and try it, and make notes about where they get stuck or confused. 
- [ ] Edit everything for clarity.
- [ ] @npaton @amaatouq review PR

**Comment by npaton** [comment]
Fantastic! Thank you so much for this. A good first tutorial for v2 is sorely needed.

I've found the "Diátaxis" framework for technical documentation to be a valuable approach: https://diataxis.fr. It is worth a read, and there's a section dedicated to Tutorials that is very helpful.

I've looked through the prisoner's dilemma demo repo and it looks good to me. It is simple enough, introducing factors, treatments, simple backend logic, and having different views for each stage. 👍 

For writing, you can work with markdown files from this repo, or you can use the WYSIWYG editor on Gitbook, which is a nicer experience. In there, it works similarly to Github, you make a branch and submit it for review when you're ready. For that, I'll need the emails of whoever will be editing or reviewing. You can send me those through Slack.

**Comment by JamesPHoughton** [comment]
Need some WSL specific pieces:
- enabling copy/paste in WSL 
- installing node on WSL

**Comment by JamesPHoughton** [comment]
To add to tutorial:
- [ ] looks like nicolas has added additional boilerplate code to the demo experiment, we need to figure out what we need to add/change in the tutorial as recorded to take that stuff out.
- [ ] quick breakout on how to use browser console to debug client 
- [ ] links to a short tutorial on how to use the chrome debugger, set a breakpoint, look at the

**Comment by JamesPHoughton** [comment]
Prepare to show off and discuss the tutorial writeup and your process for using and learning empirica at the thursday working session, @gumillie222 @mykoal

**Comment by JamesPHoughton** [comment]
Complete here: https://docs.empirica.ly/tutorials/beginner-experiment-prisoners-dilemma
